## Configuracion de Spring
spring:
  application:
    name: ms-inventory-elastic-books

## Configuracion de Instancia 
server:
  port: 8090
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-inventory-books-es

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST:books-search-6587849147.us-east-1.bonsaisearch.net:443}
  credentials:
    user: ${ELASTICSEARCH_USER:ci6b09zw3k}
    password: ${ELASTICSEARCH_PWD:rsz8y7cyg}
logging:
  level:
    tracer: TRACE